Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
ModuleNotFoundError: No module named 'util'
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
