Traceback (most recent call last):
  File "/home/minseokhwan/multilayer_scintillator/run_phantom_geant4.py", line 30, in <module>
    from mpi4py import MPI
ImportError: libmpi.so.12: cannot open shared object file: No such file or directory
