Traceback (most recent call last):
  File "/home/minseokhwan/multilayer_scintillator/run_phantom_geant4.py", line 1563, in <module>
    simulation.cmake()
  File "/home/minseokhwan/multilayer_scintillator/run_phantom_geant4.py", line 149, in cmake
    proc = subprocess.Popen(["cmake", ".."])
  File "/opt/anaconda3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
