
### Collecting Simulation Data
    0Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 367, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=42)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 329, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 313, in read_output
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 367, in <module>
    assert False
AssertionError
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=42)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 329, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 313, in read_output
    assert False
AssertionError
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 367, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=42)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 329, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 313, in read_output
    assert False
AssertionError
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 367, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=42)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 329, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 313, in read_output
    assert False
AssertionError
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 367, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 367, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=42)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 329, in collect_simulation_data
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=42)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 329, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 313, in read_output
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 313, in read_output
    assert False
AssertionError
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 367, in <module>
    assert False
AssertionError
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=42)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 329, in collect_simulation_data
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 367, in <module>
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 313, in read_output
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=42)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 329, in collect_simulation_data
    assert False
AssertionError
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 313, in read_output
    assert False
AssertionError
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 367, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 367, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 367, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=42)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 329, in collect_simulation_data
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=42)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 329, in collect_simulation_data
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=42)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 329, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 313, in read_output
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 313, in read_output
    assert False
AssertionError
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 313, in read_output
    assert False
AssertionError
    assert False
AssertionError
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 367, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=42)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 329, in collect_simulation_data
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 367, in <module>
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 313, in read_output
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=42)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 329, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 313, in read_output
    assert False
AssertionError
    assert False
AssertionError
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 367, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=42)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 329, in collect_simulation_data
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 367, in <module>
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 313, in read_output
    assert False
AssertionError
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=42)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 329, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 313, in read_output
    assert False
AssertionError
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 367, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=42)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 329, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 313, in read_output
    assert False
AssertionError
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 367, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=42)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 329, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 313, in read_output
    assert False
AssertionError
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 367, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=42)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 329, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 313, in read_output
    assert False
AssertionError
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 367, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=42)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 329, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 313, in read_output
    assert False
AssertionError
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 367, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=42)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 329, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 313, in read_output
    assert False
AssertionError
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 367, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=42)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 329, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 313, in read_output
    assert False
AssertionError
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 367, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=42)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 329, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 313, in read_output
    assert False
AssertionError
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 367, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=42)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 329, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 313, in read_output
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 367, in <module>
    assert False
AssertionError
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=42)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 329, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 313, in read_output
    assert False
AssertionError
