Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 341, in <module>
    os.mkdir(directory + "/data/" + identifier)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 364, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 364, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=1000)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 326, in collect_simulation_data
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=1000)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 326, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 299, in read_output
    np.savez(directory + "/data/" + self.identifier + "/geant4_data_" + str(comm.rank + self.rank_start),
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 639, in savez
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 299, in read_output
    np.savez(directory + "/data/" + self.identifier + "/geant4_data_" + str(comm.rank + self.rank_start),
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 639, in savez
    _savez(file, args, kwds, False)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 736, in _savez
    _savez(file, args, kwds, False)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 736, in _savez
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 364, in <module>
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 364, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 364, in <module>
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1248, in __init__
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1248, in __init__
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 364, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=1000)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 326, in collect_simulation_data
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=1000)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 326, in collect_simulation_data
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=1000)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 326, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 299, in read_output
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 364, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 364, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 364, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=1000)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 326, in collect_simulation_data
    np.savez(directory + "/data/" + self.identifier + "/geant4_data_" + str(comm.rank + self.rank_start),
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 639, in savez
    _savez(file, args, kwds, False)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 736, in _savez
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=1000)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 326, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 299, in read_output
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=1000)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 326, in collect_simulation_data
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=1000)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 326, in collect_simulation_data
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1248, in __init__
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 299, in read_output
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 299, in read_output
    np.savez(directory + "/data/" + self.identifier + "/geant4_data_" + str(comm.rank + self.rank_start),
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 639, in savez
    _savez(file, args, kwds, False)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 736, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1248, in __init__
    np.savez(directory + "/data/" + self.identifier + "/geant4_data_" + str(comm.rank + self.rank_start),
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 639, in savez
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 364, in <module>
    _savez(file, args, kwds, False)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 736, in _savez
    np.savez(directory + "/data/" + self.identifier + "/geant4_data_" + str(comm.rank + self.rank_start),
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 639, in savez
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 299, in read_output
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 299, in read_output
    _savez(file, args, kwds, False)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 736, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 299, in read_output
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1248, in __init__
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1248, in __init__
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 364, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=1000)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 326, in collect_simulation_data
    np.savez(directory + "/data/" + self.identifier + "/geant4_data_" + str(comm.rank + self.rank_start),
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 639, in savez
    _savez(file, args, kwds, False)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 736, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1248, in __init__
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 299, in read_output
    np.savez(directory + "/data/" + self.identifier + "/geant4_data_" + str(comm.rank + self.rank_start),
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 639, in savez
    np.savez(directory + "/data/" + self.identifier + "/geant4_data_" + str(comm.rank + self.rank_start),
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 639, in savez
    _savez(file, args, kwds, False)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 736, in _savez
    _savez(file, args, kwds, False)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 736, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1248, in __init__
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=1000)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 326, in collect_simulation_data
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1248, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV/geant4_data_9.npz'
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV/geant4_data_4.npz'
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV/geant4_data_8.npz'
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV/geant4_data_5.npz'
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV/geant4_data_6.npz'
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV/geant4_data_7.npz'
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV/geant4_data_10.npz'
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV/geant4_data_2.npz'
    np.savez(directory + "/data/" + self.identifier + "/geant4_data_" + str(comm.rank + self.rank_start),
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 639, in savez
    _savez(file, args, kwds, False)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 736, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1248, in __init__
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 299, in read_output
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV/geant4_data_11.npz'
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV/geant4_data_1.npz'
    np.savez(directory + "/data/" + self.identifier + "/geant4_data_" + str(comm.rank + self.rank_start),
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 639, in savez
    _savez(file, args, kwds, False)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 736, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1248, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV/geant4_data_13.npz'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 364, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=1000)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 326, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 299, in read_output
    np.savez(directory + "/data/" + self.identifier + "/geant4_data_" + str(comm.rank + self.rank_start),
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 639, in savez
    _savez(file, args, kwds, False)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 736, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1248, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV/geant4_data_14.npz'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 364, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=1000)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 326, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 299, in read_output
    np.savez(directory + "/data/" + self.identifier + "/geant4_data_" + str(comm.rank + self.rank_start),
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 639, in savez
    _savez(file, args, kwds, False)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 736, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1248, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV/geant4_data_16.npz'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 364, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 364, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=1000)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 326, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 299, in read_output
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=1000)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 326, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 299, in read_output
    np.savez(directory + "/data/" + self.identifier + "/geant4_data_" + str(comm.rank + self.rank_start),
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 639, in savez
    _savez(file, args, kwds, False)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 736, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1248, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV/geant4_data_23.npz'
    np.savez(directory + "/data/" + self.identifier + "/geant4_data_" + str(comm.rank + self.rank_start),
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 639, in savez
    _savez(file, args, kwds, False)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 736, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1248, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV/geant4_data_15.npz'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 364, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=1000)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 326, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 299, in read_output
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 364, in <module>
    np.savez(directory + "/data/" + self.identifier + "/geant4_data_" + str(comm.rank + self.rank_start),
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 639, in savez
    _savez(file, args, kwds, False)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 736, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1248, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV/geant4_data_18.npz'
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=1000)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 326, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 299, in read_output
    np.savez(directory + "/data/" + self.identifier + "/geant4_data_" + str(comm.rank + self.rank_start),
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 639, in savez
    _savez(file, args, kwds, False)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 736, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1248, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV/geant4_data_20.npz'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 364, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=1000)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 326, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 299, in read_output
    np.savez(directory + "/data/" + self.identifier + "/geant4_data_" + str(comm.rank + self.rank_start),
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 639, in savez
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 364, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 364, in <module>
    _savez(file, args, kwds, False)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 736, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1248, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV/geant4_data_22.npz'
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=1000)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 326, in collect_simulation_data
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=1000)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 326, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 299, in read_output
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 299, in read_output
    np.savez(directory + "/data/" + self.identifier + "/geant4_data_" + str(comm.rank + self.rank_start),
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 639, in savez
    _savez(file, args, kwds, False)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 736, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1248, in __init__
    np.savez(directory + "/data/" + self.identifier + "/geant4_data_" + str(comm.rank + self.rank_start),
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 639, in savez
    _savez(file, args, kwds, False)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 736, in _savez
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV/geant4_data_21.npz'
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1248, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV/geant4_data_17.npz'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 364, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=1000)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 326, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 299, in read_output
    np.savez(directory + "/data/" + self.identifier + "/geant4_data_" + str(comm.rank + self.rank_start),
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 639, in savez
    _savez(file, args, kwds, False)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 736, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1248, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV/geant4_data_19.npz'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 364, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=1000)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 326, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 299, in read_output
    np.savez(directory + "/data/" + self.identifier + "/geant4_data_" + str(comm.rank + self.rank_start),
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 639, in savez
    _savez(file, args, kwds, False)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 736, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1248, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV/geant4_data_12.npz'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 364, in <module>
    simulation.collect_simulation_data(Nreps=100, Nruns_per_energy=1000)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 326, in collect_simulation_data
    self.read_output(Nruns_per_energy)
  File "/home/minseokhwan/xray_projects/xray_scattering_discrimination/run_data_collection.py", line 299, in read_output
    np.savez(directory + "/data/" + self.identifier + "/geant4_data_" + str(comm.rank + self.rank_start),
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 639, in savez
    _savez(file, args, kwds, False)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 736, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/home/minseokhwan/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/zipfile.py", line 1248, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/xray_scattering_discrimination/data/YAGCe_150keV/geant4_data_3.npz'
